[server]
port = 9000
logger = true

[broker]
broker = "amqp://guest:guest@localhost:5672/"
result_backend = "amqp"
results_expire_in = 3600000
exchange = "atlantic"
exchange_type = "direct"
default_queue = "code_analysis"
binding_key = "code_analysis"
